# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI-CD

env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v6
    - uses: actions/checkout@v3
    - name: Use Node.js 18.12.0
      uses: actions/setup-node@v3
      with:
        node-version: '18.12.0'
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test      
    
    - name: Build Docker image main
      if: steps.branch-name.outputs.is_default == 'true'
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: false
        tags: latest
    
    - name: Build Docker image PR
      if: steps.branch-name.outputs.is_default == 'false'
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: false
        tags: ${{ steps.branch-name.outputs.current_branch }}
