name: release

on: 
  push:
   branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v2'

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false

          # ${{ steps.meta.outputs.newTag }}