name: release

on: 
  push:
   branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: create release tag
        uses: K-Phoen/semver-release-action@v1.2.0
        with:
          release_branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
