name: release

env:
 REGISTRY: ghcr.io
 IMAGE_NAME: ${{ github.repository }}

on: 
  push:
   branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.12.0
      uses: actions/setup-node@v3
      with:
        node-version: '18.12.0'
        cache: 'npm'
    
    - run: npm ci
    - run: npm test
    
  create_publish_docker:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v3'
      
      - name: 'Get current tag'
        id: currenttag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: 0.0.0
      
      - name: 'Get next version'
        id: semvers
        uses: WyriHaximus/github-action-next-semvers@v1
        with:
          version: ${{ steps.currenttag.outputs.tag }}
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.semvers.outputs.v_patch }}
          release_name: Release ${{ steps.semvers.outputs.v_patch }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: true
      
      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            ${{ steps.semvers.outputs.v_patch }}

      - name: Build and publish Docker image 
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          push: true
          tags: ${{steps.semvers.outputs.v_patch }}
          labels: ${{ steps.meta.outputs.labels }}
          
      - name: Rollback Release
        if: failure()
        uses: author/action-rollback@1.0.0
        with:
          tag: ${{steps.semvers.outputs.v_patch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
